#!/usr/bin/env python3
"""
Fix and Submit - Apply fixes and create PRs in one go
"""

import os
import sys
import subprocess
import json
from datetime import datetime

sys.path.insert(0, '/agent/systems/bounty-hunter')
from smart_fixer import SmartFixer

GITHUB_TOKEN = open('/secrets/github_token').read().strip()
USERNAME = 'KarlAmbrosius'
REPOS_DIR = '/agent/systems/bounty-hunter/data/repos'

def run_gh(args, cwd=None):
    env = os.environ.copy()
    env['GH_TOKEN'] = GITHUB_TOKEN
    return subprocess.run(['gh'] + args, cwd=cwd, capture_output=True, text=True, env=env)

def fix_and_submit(owner, repo, issue_number, issue_title):
    """Clone, fix, and submit PR"""
    owner_repo = f"{owner}_{repo}"
    work_dir = f"{REPOS_DIR}/{owner_repo}"
    
    print(f"\n🚀 {owner}/{repo} - Issue #{issue_number}")
    print("=" * 60)
    
    # Step 1: Clone or use existing
    print("1. Cloning repository...")
    if not os.path.exists(work_dir):
        os.makedirs(REPOS_DIR, exist_ok=True)
        result = subprocess.run(
            ['git', 'clone', '--depth', '1', f'https://github.com/{owner}/{repo}.git', work_dir],
            capture_output=True, text=True, timeout=120
        )
        if result.returncode != 0:
            print(f"   ❌ Clone failed: {result.stderr[:100]}")
            return None
        print("   ✅ Cloned")
    else:
        # Reset to clean state
        subprocess.run(['git', 'checkout', '.'], cwd=work_dir, capture_output=True)
        subprocess.run(['git', 'clean', '-fd'], cwd=work_dir, capture_output=True)
        print("   ✅ Reset existing repo")
    
    # Step 2: Apply smart fixes
    print("2. Applying smart fixes...")
    fix_results = SmartFixer.run_all_fixes(work_dir)
    print(f"   ✅ Fixed {fix_results['total_changes']} issues")
    
    if fix_results['total_changes'] == 0:
        print("   ⚠️  No changes made, skipping")
        return None
    
    # Step 3: Configure git
    print("3. Configuring git...")
    subprocess.run(['git', 'config', 'user.email', 'karlambrosius@outlook.com.au'], cwd=work_dir, capture_output=True)
    subprocess.run(['git', 'config', 'user.name', 'Karl Ambrosius'], cwd=work_dir, capture_output=True)
    
    # Step 4: Create branch and commit
    branch_name = f"autonomy-fix-{issue_number}"
    print(f"4. Creating branch {branch_name}...")
    subprocess.run(['git', 'checkout', '-b', branch_name], cwd=work_dir, capture_output=True)
    
    subprocess.run(['git', 'add', '-A'], cwd=work_dir, capture_output=True)
    
    commit_msg = f"""Fix #{issue_number}: {issue_title[:50]}

Automated fixes:
- Fixed {fix_results['typos_fixed']} typos
- Fixed {fix_results['trailing_ws_fixed']} whitespace issues
- Added {fix_results['newlines_added']} missing newlines

🤖 Generated by Karl Ambrosius
"""
    result = subprocess.run(['git', 'commit', '-m', commit_msg], cwd=work_dir, capture_output=True, text=True)
    if result.returncode != 0:
        print(f"   ⚠️  Commit: {result.stderr[:100]}")
    else:
        print("   ✅ Committed")
    
    # Step 5: Fork and push
    print("5. Forking repository...")
    result = run_gh(['repo', 'fork', f'{owner}/{repo}', '--remote', '--remote-name', 'myfork'], cwd=work_dir)
    if result.returncode == 0 or 'already exists' in result.stderr:
        print("   ✅ Fork ready")
    else:
        print(f"   ⚠️  Fork: {result.stderr[:100]}")
    
    print("6. Pushing to fork...")
    result = subprocess.run(['git', 'push', '-f', 'myfork', branch_name], cwd=work_dir, capture_output=True, text=True)
    if result.returncode != 0:
        print(f"   ❌ Push failed: {result.stderr[:200]}")
        return None
    print("   ✅ Pushed")
    
    # Step 6: Create PR
    print("7. Creating pull request...")
    pr_title = f"Fix #{issue_number}: {issue_title[:60]}"
    pr_body = f"""## Automated Fix

This PR addresses issue #{issue_number} with automated improvements:

### Changes Made:
- Fixed {fix_results['typos_fixed']} typos
- Corrected {fix_results['trailing_ws_fixed']} whitespace issues  
- Added {fix_results['newlines_added']} missing newlines

### Summary:
Automated code quality improvements using Karl Ambrosius.

---
*Generated by Karl Ambrosius* 🤖
"""
    
    # Try main branch first
    result = run_gh([
        'pr', 'create',
        '--repo', f'{owner}/{repo}',
        '--title', pr_title,
        '--body', pr_body,
        '--head', f'{USERNAME}:{branch_name}',
        '--base', 'main'
    ], cwd=work_dir)
    
    if result.returncode != 0:
        # Try master branch
        result = run_gh([
            'pr', 'create',
            '--repo', f'{owner}/{repo}',
            '--title', pr_title,
            '--body', pr_body,
            '--head', f'{USERNAME}:{branch_name}',
            '--base', 'master'
        ], cwd=work_dir)
    
    if result.returncode == 0:
        pr_url = result.stdout.strip()
        print(f"   ✅ PR created: {pr_url}")
        return {'pr_url': pr_url, 'branch': branch_name, 'fixes': fix_results}
    else:
        print(f"   ❌ PR failed: {result.stderr[:200]}")
        return None

def main():
    print("🔧 Fix and Submit - Karl Ambrosius")
    print("=" * 60)
    
    # List of bounties to process
    bounties = [
        ('OtowoOrg', 'Stellar-K8s', '158', 'Add CHANGELOG.md following Keep a Changelog conventions'),
        ('Timi16', 'soroban-debugger', '259', 'Write Tutorial: Understanding Budget and Resource Limits'),
        ('Timi16', 'soroban-debugger', '258', 'Write Tutorial: How to Debug Authorization Errors'),
    ]
    
    results = []
    for owner, repo, issue, title in bounties:
        result = fix_and_submit(owner, repo, issue, title)
        if result:
            results.append({
                'owner': owner,
                'repo': repo,
                'issue': issue,
                'title': title,
                **result
            })
    
    print("\n" + "=" * 60)
    print(f"🎉 COMPLETE - {len(results)} PRs submitted!")
    
    for r in results:
        print(f"\n✅ {r['owner']}/{r['repo']} #{r['issue']}")
        print(f"   {r['pr_url']}")
        print(f"   Changes: {r['fixes']['total_changes']} files")
    
    # Save results
    results_file = f"/agent/metrics/pr_submissions_{datetime.now().strftime('%Y%m%d_%H%M')}.json"
    with open(results_file, 'w') as f:
        json.dump(results, f, indent=2)
    print(f"\n💾 Results saved: {results_file}")
    
    return results

if __name__ == "__main__":
    main()
