#!/usr/bin/env python3
"""
GitHub CLI Automation for Bounty Hunter
Uses subprocess to call gh commands with token authentication
"""

import os
import subprocess
import json
from datetime import datetime

GITHUB_TOKEN = open('/secrets/github_token').read().strip()
USERNAME = 'kambrosgroup'
REPOS_DIR = '/agent/systems/bounty-hunter/data/repos'

def run_gh_command(args, cwd=None, env=None):
    """Run a gh command with authentication"""
    env_vars = os.environ.copy()
    env_vars['GH_TOKEN'] = GITHUB_TOKEN
    if env:
        env_vars.update(env)
    
    cmd = ['gh'] + args
    result = subprocess.run(cmd, cwd=cwd, capture_output=True, text=True, env=env_vars)
    return result

def submit_pr_for_repo(owner_repo, issue_number, issue_title):
    """Submit a PR for a specific repo using gh CLI"""
    owner, repo = owner_repo.split('_', 1)
    work_dir = f"{REPOS_DIR}/{owner_repo}"
    
    if not os.path.exists(work_dir):
        print(f"❌ Repo not found: {work_dir}")
        return None
    
    print(f"\n🚀 Processing {owner}/{repo} (Issue #{issue_number})")
    print("=" * 60)
    
    # Step 1: Check git status
    print("1. Checking git status...")
    result = subprocess.run(['git', 'status', '--short'], cwd=work_dir, capture_output=True, text=True)
    if not result.stdout.strip():
        print("   ⚠️  No changes to commit")
        return None
    
    changes = result.stdout.strip().split('\n')
    print(f"   ✅ {len(changes)} files modified")
    
    # Step 2: Configure git
    print("2. Configuring git...")
    subprocess.run(['git', 'config', 'user.email', 'autonomy-claw@openclaw.ai'], cwd=work_dir, capture_output=True)
    subprocess.run(['git', 'config', 'user.name', 'AUTONOMY-CLAW'], cwd=work_dir, capture_output=True)
    
    # Step 3: Create branch
    branch_name = f"autonomy-fix-{issue_number}"
    print(f"3. Creating branch: {branch_name}...")
    subprocess.run(['git', 'checkout', '-b', branch_name], cwd=work_dir, capture_output=True)
    
    # Step 4: Stage and commit
    print("4. Committing changes...")
    subprocess.run(['git', 'add', '-A'], cwd=work_dir, capture_output=True)
    
    commit_msg = f"""Fix #{issue_number}: {issue_title[:50]}

Automated fixes:
- Fixed typos
- Corrected formatting
- Added missing newlines

🤖 Generated by AUTONOMY-CLAW
"""
    result = subprocess.run(['git', 'commit', '-m', commit_msg], cwd=work_dir, capture_output=True, text=True)
    if result.returncode != 0:
        print(f"   ⚠️  Commit issue: {result.stderr[:100]}")
    else:
        print("   ✅ Changes committed")
    
    # Step 5: Fork repo using gh
    print(f"5. Forking {owner}/{repo}...")
    result = run_gh_command(['repo', 'fork', f'{owner}/{repo}', '--remote', '--remote-name', 'myfork'], cwd=work_dir)
    
    if result.returncode == 0:
        print("   ✅ Fork created/updated")
    else:
        # Try to add remote manually
        print(f"   ⚠️  Fork command output: {result.stderr[:100]}")
        # Add remote anyway
        subprocess.run(['git', 'remote', 'add', 'myfork', f'https://github.com/{USERNAME}/{repo}.git'], 
                      cwd=work_dir, capture_output=True)
    
    # Step 6: Push to fork
    print(f"6. Pushing to fork...")
    result = subprocess.run(['git', 'push', '-f', 'myfork', branch_name], 
                           cwd=work_dir, capture_output=True, text=True)
    
    if result.returncode != 0:
        print(f"   ❌ Push failed: {result.stderr[:200]}")
        return None
    
    print("   ✅ Pushed to fork")
    
    # Step 7: Create PR using gh
    print(f"7. Creating pull request...")
    pr_title = f"Fix #{issue_number}: {issue_title[:60]}"
    pr_body = f"""## Automated Fix

This PR addresses issue #{issue_number}.

### Changes Made:
- Fixed typos and spelling errors
- Corrected formatting issues
- Added missing newlines

### Files Modified:
See commit diff for details.

---
*Generated by AUTONOMY-CLAW* 🤖
"""
    
    result = run_gh_command([
        'pr', 'create',
        '--repo', f'{owner}/{repo}',
        '--title', pr_title,
        '--body', pr_body,
        '--head', f'{USERNAME}:{branch_name}',
        '--base', 'main'
    ], cwd=work_dir)
    
    if result.returncode == 0:
        pr_url = result.stdout.strip()
        print(f"   ✅ PR created: {pr_url}")
        return {'pr_url': pr_url, 'branch': branch_name}
    else:
        # Try with master as base
        result = run_gh_command([
            'pr', 'create',
            '--repo', f'{owner}/{repo}',
            '--title', pr_title,
            '--body', pr_body,
            '--head', f'{USERNAME}:{branch_name}',
            '--base', 'master'
        ], cwd=work_dir)
        
        if result.returncode == 0:
            pr_url = result.stdout.strip()
            print(f"   ✅ PR created (to master): {pr_url}")
            return {'pr_url': pr_url, 'branch': branch_name}
        else:
            print(f"   ❌ PR creation failed: {result.stderr[:200]}")
            return None

def main():
    print("🎯 GitHub CLI Bounty Submitter")
    print("=" * 60)
    
    # Check gh is installed
    result = subprocess.run(['gh', '--version'], capture_output=True)
    if result.returncode != 0:
        print("❌ GitHub CLI not found")
        return
    
    print(f"✅ GitHub CLI: {result.stdout.decode().split()[2]}")
    
    # Define the repos ready for submission
    submissions = [
        {
            'owner_repo': 'OtowoOrg_Stellar-K8s',
            'issue_number': '158',
            'issue_title': 'Add CHANGELOG.md following Keep a Changelog conventions'
        },
        {
            'owner_repo': 'Timi16_soroban-debugger',
            'issue_number': '259',
            'issue_title': 'Write Tutorial: Understanding Budget and Resource Limits'
        },
        {
            'owner_repo': 'Timi16_soroban-debugger',
            'issue_number': '258',
            'issue_title': 'Write Tutorial: How to Debug Authorization Errors'
        },
    ]
    
    results = []
    for sub in submissions:
        result = submit_pr_for_repo(
            sub['owner_repo'],
            sub['issue_number'],
            sub['issue_title']
        )
        if result:
            results.append({**sub, **result})
    
    print("\n" + "=" * 60)
    print(f"🎉 Submission Complete!")
    print(f"   PRs created: {len(results)}")
    
    for r in results:
        print(f"\n   ✅ {r['owner_repo']} #{r['issue_number']}")
        print(f"      {r['pr_url']}")
    
    # Save results
    results_file = f"/agent/metrics/pr_submissions_{datetime.now().strftime('%Y%m%d_%H%M')}.json"
    with open(results_file, 'w') as f:
        json.dump(results, f, indent=2)
    print(f"\n   Results saved to: {results_file}")

if __name__ == "__main__":
    main()
