#!/bin/bash
# Setup AUTONOMY-CLAW GitHub Actions Workflow
# This script sets up the complete automation for 302 bounty opportunities

set -e

echo "🚀 AUTONOMY-CLAW GitHub Actions Setup"
echo "======================================"
echo ""

# Check prerequisites
echo "Checking prerequisites..."

if ! command -v gh &> /dev/null; then
    echo "❌ GitHub CLI not found. Please install it first:"
    echo "   https://cli.github.com/"
    exit 1
fi

if ! gh auth status &> /dev/null; then
    echo "❌ Not authenticated with GitHub CLI. Please run:"
    echo "   gh auth login"
    exit 1
fi

echo "✅ GitHub CLI authenticated"
echo ""

# Get repository info
echo "Setting up repository..."
REPO=$(gh repo view --json nameWithOwner -q .nameWithOwner)
echo "Repository: $REPO"
echo ""

# Create workflow directory
echo "Creating workflow files..."
mkdir -p .github/workflows
mkdir -p .github/scripts

# Copy workflow files (already created)
echo "✅ Workflow files ready"
echo ""

# Set up secrets
echo "Setting up GitHub Secrets..."
echo ""

# Check for existing secrets
echo "Checking existing secrets..."
SECRETS=$(gh secret list 2>/dev/null || echo "")

if ! echo "$SECRETS" | grep -q "GITHUB_TOKEN"; then
    echo "⚠️  GITHUB_TOKEN secret not found"
    echo "   This is automatically provided by GitHub Actions"
fi

echo ""
echo "Optional secrets to set:"
echo "  - PAYPAL_CLIENT_ID: For SaaS subscription integration"
echo "  - PAYPAL_SECRET: For SaaS subscription integration"
echo ""
read -p "Do you want to set PayPal secrets now? (y/n) " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]; then
    read -p "Enter PayPal Client ID: " PAYPAL_CLIENT_ID
    read -p "Enter PayPal Secret: " PAYPAL_SECRET
    
    echo "$PAYPAL_CLIENT_ID" | gh secret set PAYPAL_CLIENT_ID
    echo "$PAYPAL_SECRET" | gh secret set PAYPAL_SECRET
    
    echo "✅ PayPal secrets set"
fi

echo ""

# Commit workflow files
echo "Committing workflow files..."
git add .github/
git commit -m "Add AUTONOMY-CLAW bounty hunter workflows

- Automated bounty hunting for 302+ opportunities
- Verified fix application before PR submission
- Auto typo scanning and fixing
- PR monitoring and auto-response
- Daily reporting
- Container deployment to GHCR

Workflows:
- bounty-hunter.yml: Main workflow (runs every 6 hours)
- container-deploy.yml: Build and deploy container
- auto-respond.yml: Auto-respond to PR comments

Generated by AUTONOMY-CLAW 🤖" || echo "Nothing to commit"

echo ""
echo "Pushing to GitHub..."
git push

echo ""
echo "======================================"
echo "✅ Setup Complete!"
echo ""
echo "Next steps:"
echo "1. Go to https://github.com/$REPO/actions"
echo "2. Enable GitHub Actions if not already enabled"
echo "3. Run the 'AUTONOMY-CLAW Bounty Hunter' workflow manually"
echo "4. Check the 'Actions' tab for results"
echo ""
echo "The workflow will:"
echo "  - Run every 6 hours automatically"
echo "  - Process up to 10 high-quality bounties per run"
echo "  - Submit verified PRs only"
echo "  - Monitor existing PRs"
echo "  - Generate daily reports"
echo ""
echo "Container image:"
echo "  ghcr.io/$REPO/bounty-hunter:latest"
echo ""
echo "To run manually:"
echo "  gh workflow run bounty-hunter.yml"
echo ""
echo "To run specific bounty type:"
echo "  gh workflow run bounty-hunter.yml -f bounty_type=documentation"
echo ""
