#!/usr/bin/env python3
"""
Verified Bounty Submitter - AUTONOMY-CLAW
Only submits PRs after verifying fixes actually address the issue
"""

import os
import sys
import subprocess
import json
import time
from datetime import datetime

sys.path.insert(0, '/agent/systems/bounty-hunter')
from verified_fixer import VerifiedFixer

GITHUB_TOKEN = open('/secrets/github_token').read().strip()
USERNAME = 'kambrosgroup'
REPOS_DIR = '/agent/systems/bounty-hunter/data/repos'

def run_gh(args, cwd=None):
    env = os.environ.copy()
    env['GH_TOKEN'] = GITHUB_TOKEN
    return subprocess.run(['gh'] + args, cwd=cwd, capture_output=True, text=True, env=env)

def get_issue_details(owner, repo, issue_number):
    """Fetch issue details from GitHub API"""
    import requests
    url = f"https://api.github.com/repos/{owner}/{repo}/issues/{issue_number}"
    headers = {'Authorization': f'token {GITHUB_TOKEN}', 'Accept': 'application/vnd.github.v3+json'}
    
    try:
        response = requests.get(url, headers=headers, timeout=30)
        if response.status_code == 200:
            data = response.json()
            return {
                'title': data.get('title', ''),
                'body': data.get('body', '')
            }
    except Exception as e:
        print(f"   Error fetching issue: {e}")
    
    return None

def submit_verified_pr(owner, repo, issue_number, issue_title):
    """Clone, verify fix, and submit PR only if fix is valid"""
    owner_repo = f"{owner}_{repo}"
    work_dir = f"{REPOS_DIR}/{owner_repo}"
    
    print(f"\n{'='*70}")
    print(f"🚀 Processing {owner}/{repo} - Issue #{issue_number}")
    print(f"   Title: {issue_title[:60]}")
    print('='*70)
    
    # Step 1: Clone fresh
    print("\n1. Cloning repository...")
    if os.path.exists(work_dir):
        subprocess.run(['rm', '-rf', work_dir], capture_output=True)
    
    os.makedirs(REPOS_DIR, exist_ok=True)
    result = subprocess.run(
        ['git', 'clone', '--depth', '1', f'https://github.com/{owner}/{repo}.git', work_dir],
        capture_output=True, text=True, timeout=120
    )
    if result.returncode != 0:
        print(f"   ❌ Clone failed: {result.stderr[:100]}")
        return None
    print("   ✅ Cloned")
    
    # Step 2: Get full issue details
    print("\n2. Fetching issue details...")
    issue_details = get_issue_details(owner, repo, issue_number)
    if not issue_details:
        print("   ⚠️  Could not fetch issue details, using title only")
        issue_details = {'title': issue_title, 'body': ''}
    else:
        print("   ✅ Got issue details")
    
    # Step 3: Analyze and apply verified fix
    print("\n3. Analyzing and applying fix...")
    fix_result = VerifiedFixer.fix_issue(
        work_dir,
        issue_details['title'],
        issue_details['body']
    )
    
    if not fix_result['success']:
        print(f"   ❌ Fix failed: {fix_result['reason']}")
        print(f"   Analysis: {fix_result['analysis']}")
        return None
    
    if not fix_result['changes']:
        print("   ⚠️  No changes made - issue may already be fixed or not applicable")
        return None
    
    print(f"   ✅ Fix applied and verified!")
    print(f"   Changes ({len(fix_result['changes'])}):")
    for change in fix_result['changes'][:5]:
        print(f"      - {change}")
    if len(fix_result['changes']) > 5:
        print(f"      ... and {len(fix_result['changes']) - 5} more")
    
    # Step 4: Configure git
    print("\n4. Configuring git...")
    subprocess.run(['git', 'config', 'user.email', 'autonomy-claw@openclaw.ai'], cwd=work_dir, capture_output=True)
    subprocess.run(['git', 'config', 'user.name', 'AUTONOMY-CLAW'], cwd=work_dir, capture_output=True)
    
    # Step 5: Create branch and commit
    branch_name = f"autonomy-fix-{issue_number}"
    print(f"\n5. Creating branch '{branch_name}' and committing...")
    subprocess.run(['git', 'checkout', '-b', branch_name], cwd=work_dir, capture_output=True)
    subprocess.run(['git', 'add', '-A'], cwd=work_dir, capture_output=True)
    
    # Build commit message with details
    changes_summary = '\n'.join([f"- {c}" for c in fix_result['changes'][:10]])
    commit_msg = f"""Fix #{issue_number}: {issue_title[:50]}

This PR addresses the issue with the following changes:

{changes_summary}

Fix type: {fix_result['analysis']['fix_type']}
Confidence: {fix_result['analysis']['confidence']:.0%}
Verified: ✅

🤖 Generated by AUTONOMY-CLAW
"""
    
    result = subprocess.run(['git', 'commit', '-m', commit_msg], cwd=work_dir, capture_output=True, text=True)
    if result.returncode == 0:
        print("   ✅ Committed")
    else:
        print(f"   ⚠️  Commit issue: {result.stderr[:100]}")
    
    # Step 6: Show diff summary
    print("\n6. Changes summary:")
    result = subprocess.run(['git', 'diff', '--stat', 'HEAD~1'], cwd=work_dir, capture_output=True, text=True)
    if result.stdout:
        for line in result.stdout.strip().split('\n')[:10]:
            print(f"   {line}")
    
    # Step 7: Fork repo
    print(f"\n7. Forking {owner}/{repo}...")
    result = run_gh(['repo', 'fork', f'{owner}/{repo}', '--remote=false'], cwd=work_dir)
    if result.returncode == 0 or 'already exists' in result.stderr.lower():
        print("   ✅ Fork ready")
    else:
        print(f"   ⚠️  Fork: {result.stderr[:100]}")
    
    time.sleep(2)
    
    # Step 8: Push to fork
    print("\n8. Pushing to fork...")
    fork_url = f"https://{USERNAME}:{GITHUB_TOKEN}@github.com/{USERNAME}/{repo}.git"
    subprocess.run(['git', 'remote', 'remove', 'myfork'], cwd=work_dir, capture_output=True)
    subprocess.run(['git', 'remote', 'add', 'myfork', fork_url], cwd=work_dir, capture_output=True)
    
    result = subprocess.run(['git', 'push', '-f', 'myfork', branch_name], cwd=work_dir, capture_output=True, text=True)
    if result.returncode != 0:
        print(f"   ❌ Push failed: {result.stderr[:200]}")
        return None
    print("   ✅ Pushed")
    
    # Step 9: Create PR
    print("\n9. Creating pull request...")
    pr_title = f"Fix #{issue_number}: {issue_title[:60]}"
    pr_body = f"""## Fix for Issue #{issue_number}

### Problem
{issue_details['title']}

### Solution
This PR applies the following verified fixes:

{changes_summary}

### Verification
- ✅ Fix type: {fix_result['analysis']['fix_type']}
- ✅ Confidence: {fix_result['analysis']['confidence']:.0%}
- ✅ Changes verified before submission

### Testing
Please review the changes to ensure they correctly address the issue.

---
*This PR was automatically generated by [AUTONOMY-CLAW](https://github.com/kambrosgroup) 🤖*
*The fix was verified to actually address the issue before submission*
"""
    
    for base in ['main', 'master']:
        result = run_gh([
            'pr', 'create',
            '--repo', f'{owner}/{repo}',
            '--title', pr_title,
            '--body', pr_body,
            '--head', f'{USERNAME}:{branch_name}',
            '--base', base
        ], cwd=work_dir)
        
        if result.returncode == 0:
            pr_url = result.stdout.strip()
            print(f"   ✅ PR created: {pr_url}")
            return {
                'pr_url': pr_url,
                'branch': branch_name,
                'fix_result': fix_result
            }
    
    print(f"   ❌ PR creation failed")
    return None

def main():
    print("🔧 Verified Bounty Submitter - AUTONOMY-CLAW")
    print("=" * 70)
    print("Only submits PRs after verifying fixes actually address the issue")
    print("=" * 70)
    
    # Test with one known issue first
    test_bounties = [
        ('OtowoOrg', 'Stellar-K8s', '158', 'Add CHANGELOG.md following Keep a Changelog conventions'),
    ]
    
    results = []
    for owner, repo, issue, title in test_bounties:
        result = submit_verified_pr(owner, repo, issue, title)
        if result:
            results.append({
                'owner': owner,
                'repo': repo,
                'issue': issue,
                'title': title,
                **result
            })
    
    print("\n" + "=" * 70)
    print(f"🎉 COMPLETE - {len(results)} verified PRs submitted!")
    
    for r in results:
        print(f"\n✅ {r['owner']}/{r['repo']} #{r['issue']}")
        print(f"   {r['pr_url']}")
        print(f"   Fix type: {r['fix_result']['analysis']['fix_type']}")
        print(f"   Changes: {len(r['fix_result']['changes'])}")
        print(f"   Verified: {r['fix_result']['verified']}")
    
    # Save results
    results_file = f"/agent/metrics/verified_pr_submissions_{datetime.now().strftime('%Y%m%d_%H%M')}.json"
    with open(results_file, 'w') as f:
        json.dump(results, f, indent=2)
    print(f"\n💾 Results saved: {results_file}")

if __name__ == "__main__":
    main()
